name: Daily Model Training

on:
  schedule:
    - cron: '30 16 * * *'  # Runs at 16:30 UTC every day
  workflow_dispatch:

jobs:
  train-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/IE-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ensure this matches the version in your pyproject.toml

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: DVC Pull
        run: |
          poetry run dvc pull
        env:
          DVC_REMOTE: origin  # Specify your DVC remote name if different
          DVC_AUTH: ${{ secrets.DVC_AUTH }}  # Ensure this is set in your repository secrets if authentication is needed

      - name: Fetch data
        run: poetry run python scripts/fetch_data.py

      - name: Preprocess data
        run: poetry run python scripts/preprocess_data.py

      - name: Train model
        run: poetry run python scripts/train_model.py

      - name: DVC Add data and models
        run: |
          poetry run dvc add data
          poetry run dvc add models

      - name: DVC Push
        run: poetry run dvc push -r origin

      - name: Git operations
        run: |
          git config --global user.email "github-actions-bot@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "My daily workflow pipeline" || echo "No changes to commit"
          git push
