name: Run Fetch Script Hourly

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'

jobs:
  fetch_and_process_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4 # Updated to the latest version, assuming v4 supports Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pandas
        pip install retry-requests
        pip install requests_cache
        pip install openmeteo-requests

    - name: Run fetch data script
      run: python IE-app/scripts/fetch_data.py
