name: Process and Commit Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch_process_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pandas

    - name: Run fetch data script
      run: python fetch_data.py
      working-directory: IE-app/scripts

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add IE-app/data/combined/*.csv
        git commit -m "Append data to CSV files" -a || echo "No changes to commit"
        git push
